[build-system]
requires = ["setuptools>=68", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyssp4sim"
dynamic = ["version"]
description = "SSP4SIM abi3 binary module"
requires-python = ">=3.9"
authors = [{ name = "Erik Rosenlund" }]

[project.scripts]
pyssp4sim = "pyssp4sim.cli:main"

[tool.setuptools]
packages = ["pyssp4sim"]
include-package-data = true

[tool.setuptools.package-data]
# Include the compiled extension in the package
pyssp4sim = ["*.so", "*.pyd", "*.dll", "*.dylib"]

[tool.setuptools_scm]
fallback_version = "0.0.0.dev0"
